import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white shadow-lg">
      <div className="max-w-7xl mx-auto px-4">
        <div className="flex justify-between">
          {/* Logo and main links */}
          <div className="flex space-x-7">
            {/* Logo */}
            <div>
              <Link href="/" className="flex items-center py-4 px-2">
                <Image 
                  src="/cv-logo.jpg" // Replace with your logo path
                  alt="Creative CV Logo"
                  width={120}
                  height={40}
                  className="mr-2"
                />
              </Link>
            </div>
            
            {/* Primary Nav */}
            <div className="hidden md:flex items-center space-x-1">
              <Link href="/" className="py-4 px-2 text-gray-700 hover:text-blue-500 transition duration-300">
                Home
              </Link>
              <Link href="/Templates" className="py-4 px-2 text-gray-700 hover:text-blue-500 transition duration-300">
                Templates
              </Link>
              <Link href="/Builder" className="py-4 px-2 text-gray-700 hover:text-blue-500 transition duration-300">
                Builder
              </Link>
              <Link href="/examples" className="py-4 px-2 text-gray-700 hover:text-blue-500 transition duration-300">
                Examples
              </Link>
              <Link href="/tips" className="py-4 px-2 text-gray-700 hover:text-blue-500 transition duration-300">
                Tips & Guides
              </Link>
            </div>
          </div>
          
          {/* Secondary Nav */}
          <div className="hidden md:flex items-center space-x-3">
            <Link href="/about" className="py-2 px-2 text-gray-700 hover:text-blue-500 transition duration-300">
              About
            </Link>
            <Link href="/pricing" className="py-2 px-2 text-gray-700 hover:text-blue-500 transition duration-300">
              Pricing
            </Link>
            <Link href="/login" className="py-2 px-2 text-white bg-blue-500 rounded hover:bg-blue-400 transition duration-300">
              Login
            </Link>
            <Link href="/signup" className="py-2 px-2 text-white bg-green-500 rounded hover:bg-green-400 transition duration-300">
              Sign Up
            </Link>
          </div>
          
          {/* Mobile button */}
          <div className="md:hidden flex items-center">
            <button className="outline-none mobile-menu-button">
              <svg className="w-6 h-6 text-gray-700"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
      
      {/* Mobile menu */}
      <div className="hidden mobile-menu">
        <ul className="">
          <li className="active"><Link href="/" className="block text-sm px-2 py-4 text-white bg-blue-500 font-semibold">Home</Link></li>
          <li><Link href="/templates" className="block text-sm px-2 py-4 hover:bg-blue-500 transition duration-300">Templates</Link></li>
          <li><Link href="/builder" className="block text-sm px-2 py-4 hover:bg-blue-500 transition duration-300">Builder</Link></li>
          <li><Link href="/examples" className="block text-sm px-2 py-4 hover:bg-blue-500 transition duration-300">Examples</Link></li>
          <li><Link href="/tips" className="block text-sm px-2 py-4 hover:bg-blue-500 transition duration-300">Tips & Guides</Link></li>
          <li><Link href="/about" className="block text-sm px-2 py-4 hover:bg-blue-500 transition duration-300">About</Link></li>
          <li><Link href="/pricing" className="block text-sm px-2 py-4 hover:bg-blue-500 transition duration-300">Pricing</Link></li>
        </ul>
      </div>
    </nav>
        {children}
      </body>
    </html>
  );
}
